name: hsp2_py37
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge
  - defaults
dependencies:
  - jupyterlab
  - numba
  - numpy
  - pandas>=1.0.0
  - pip
  - python>=3.7.0
  - pip:
    - tables
