name: Python application
# this is a standard setup copied from 
# https://docs.github.com/en/enterprise-server@3.10/actions/automating-builds-and-tests/building-and-testing-python
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "develop-tests", "develop-specact-speed-eq" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install hsp2
      run: |
        # install the hsp2 executable
        pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --ignore=F821 --show-source --statistics --exclude=HSP2/ACIDPH.py,build/lib/HSP2/ACIDPH.py
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest 
      run: |
        pytest tests/ptest/test_sysexit.py
        # add additional test, ex:
        # pytest tests/testcbp/HSP2results/benchmark.py
    - name: Run hsp2 test10
      run: |
        cd tests/test10/HSP2results
        hsp2 import_uci test10.uci test10.h5
        hsp2 run test10.h5
