name: Python application
# this is a standard setup copied from
# https://docs.github.com/en/enterprise-server@3.10/actions/automating-builds-and-tests/building-and-testing-python
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "develop", "develop-specact" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    - name: Install hsp2
      run: |
        # install the hsp2 executable
        pip install .[dev]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --ignore=F821 --show-source --statistics --exclude=build/*
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # python coverage
        NUMBA_DISABLE_JIT=1 pytest --cov --cov-branch --cov-report term-missing
    - name: Run hsp2 test10
      run: |
        cd tests/test10/HSP2results
        hsp2 import_uci test10.uci test10.h5
        hsp2 run test10.h5
